---
title: "Organ-Specific Cleavage Sites (Rare Only)"
author: "Mervin M Fansler"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    code_folding: show
    toc: true
    toc_float: true
---

# Initialization
## Libraries
```{r libs, message=FALSE, warning=FALSE}
library(plyranges)
library(tidyverse)
library(magrittr)
library(readxl)
```

## Parameters
```{r params}
EPSILON = 30
TPM = 5
N_CTS_LOW = 10
N_CTS_HIGH = 80

FILE_UTROME = sprintf("data/granges/utrome_gr_txs.e%d.t%d.gc25.pas3.f0.9999.w500.Rds", EPSILON, TPM)
FILE_BED = sprintf("data/bed/celltypes/celltypes.e%d.t%d.bed.gz", EPSILON, TPM)
FILE_CLASSES = "metadata/counts_celltype_tissue_mca1_1_classified.xlsx"

CLASS_NAMES = c("1"="Organ", "2"="Blood", "3"="Brain", "4"="Testis", "6"="Membrane")
```

# Load Data

## Cell Type Classes
```{r load_classes}
df_class <- read_xlsx(FILE_CLASSES) %>%
    mutate(class_id=factor(CLASS_NAMES[as.character(Organs)], levels=CLASS_NAMES),
           n_cells=rowSums(.[6:ncol(.)])) %>%
    select(celltype_id, class_id, n_cells)

map_ct_organ <- pull(df_class, class_id, celltype_id)
df_cells <- df_class %>%
    group_by(class_id) %>%
    summarize(n_cells=sum(n_cells)) %>%
    filter(!is.na(class_id))
```

## Cleavage Sites by Cell Type
```{r load_sites}
gr_sites <- read_bed(FILE_BED) %>%
    `seqlevelsStyle<-`("UCSC") %>%
    keepStandardChromosomes(pruning.mode="coarse") %>%
    anchor_center() %>%
    mutate(width=EPSILON,
           class_id=map_ct_organ[name])
```

## Mouse UTRome Transcripts
```{r load_txs, message=FALSE, warning=FALSE}
## Load all transcripts
gr_txs <- readRDS(FILE_UTROME)

## focus on cleavage sites
gr_cleavage <- gr_txs %>%
    anchor_3p %>%
    mutate(width=0,
           n_celltypes=count_overlaps_directed(., gr_sites))

df_cs_class <- gr_sites %>%
    filter(!is.na(class_id)) %>%
    group_by(class_id) %>%
    reduce_ranges_directed() %>%
    mutate(cs_gencode=count_overlaps_directed(., filter(gr_cleavage, !is_novel, n_celltypes < 10)),
           cs_novel=count_overlaps_directed(., filter(gr_cleavage, is_novel, n_celltypes < 10)),
           ) %>%
    filter(cs_gencode + cs_novel > 0) %>%
    group_by(class_id) %>%
    summarize(n_cs_gencode=sum(cs_gencode > 0),
              n_cs_novel=sum(cs_novel > 0)) %>%
    as.tibble()
```


# Plots
## Default Order
```{r plt_n_cs_cts, fig.height=3, fig.width=4}
df_cs_class %>%
    pivot_longer(cols=2:3, names_to='atlas', names_prefix='n_cs_', values_to='n_cs') %>%
    ggplot(aes(x=class_id, y=n_cs, fill=atlas)) +
    geom_bar(stat='identity', position='stack', linewidth=0.1, color='black') +
    scale_fill_manual(values=c(gencode='#cccccc', novel='#77aaee' )) +
    coord_flip() +
    labs(x=NULL, y="Cleavage Sites", fill="Source") +
    theme_bw()
```

```{r plt_n_cs_fill, fig.height=3, fig.width=4}
df_cs_class %>%
    pivot_longer(cols=2:3, names_to='atlas', names_prefix='n_cs_', values_to='n_cs') %>%
    ggplot(aes(x=class_id, y=n_cs, fill=atlas)) +
    geom_bar(stat='identity', position='fill', linewidth=0.1, color='black') +
    scale_fill_manual(values=c(gencode='#cccccc', novel='#77aaee' )) +
    coord_flip() +
    labs(x=NULL, y="Fraction of Cleavage Sites", fill="Source") +
    theme_bw()
```

## Novel Sites Order
```{r plt_n_cs_cts_novel, fig.height=3, fig.width=4}
df_cs_class %>%
    mutate(class_id=fct_reorder(class_id, n_cs_novel)) %>%
    pivot_longer(cols=2:3, names_to='atlas', names_prefix='n_cs_', values_to='n_cs') %>%
    ggplot(aes(x=class_id, y=n_cs, fill=atlas)) +
    geom_bar(stat='identity', position='stack', linewidth=0.1, color='black') +
    scale_fill_manual(values=c(gencode='#cccccc', novel='#77aaee' )) +
    coord_flip() +
    labs(x=NULL, y="Cleavage Sites", fill="Source") +
    theme_bw()
```


## Fraction of Novel Sites Order
```{r plt_n_cs_fill_novel_frac, fig.height=3, fig.width=4}
df_cs_class %>%
    mutate(class_id=fct_reorder(class_id, n_cs_novel/(n_cs_gencode+n_cs_novel))) %>%
    pivot_longer(cols=2:3, names_to='atlas', names_prefix='n_cs_', values_to='n_cs') %>%
    ggplot(aes(x=class_id, y=n_cs, fill=atlas)) +
    geom_bar(stat='identity', position='fill', linewidth=0.1, color='black') +
    scale_fill_manual(values=c(gencode='#cccccc', novel='#77aaee' )) +
    coord_flip() +
    labs(x=NULL, y="Fraction of Cleavage Sites", fill="Source") +
    theme_bw()
```

## Rates
```{r plt_n_cs_rates, fig.height=3, fig.width=4}
df_cs_class %>%
    left_join(df_cells, by="class_id") %>%
    mutate(rate_cs_gencode=1e3*n_cs_gencode/n_cells,
           rate_cs_novel=1e3*n_cs_novel/n_cells) %>%
    mutate(class_id=fct_reorder(class_id, rate_cs_novel)) %>%
    select(class_id, rate_cs_gencode, rate_cs_novel) %>%
    pivot_longer(cols=2:3, names_to='atlas', names_prefix='rate_cs_', values_to='rate_cs') %>%
    ggplot(aes(x=class_id, y=rate_cs, fill=atlas)) +
    geom_bar(stat='identity', position='stack', linewidth=0.1, color='black') +
    scale_fill_manual(values=c(gencode='#cccccc', novel='#77aaee' )) +
    coord_flip() +
    labs(x=NULL, y="Cleavage Site Detection Rate\n(Sites/1K Cells)", fill="Source") +
    theme_bw()
```


```{r plt_rate_cs_stacked, fig.height=4, fig.width=3}
df_cs_class %>%
    left_join(df_cells, by="class_id") %>%
    mutate(rate_cs_gencode=1e3*n_cs_gencode/n_cells,
           rate_cs_novel=1e3*n_cs_novel/n_cells) %>%
    mutate(class_id=fct_reorder(class_id, rate_cs_novel)) %>%
    select(class_id, rate_cs_gencode, rate_cs_novel) %>%
    pivot_longer(cols=2:3, names_to='atlas', names_prefix='rate_cs_', values_to='rate_cs') %>%
    ggplot(aes(x=atlas, y=rate_cs, fill=class_id)) +
    geom_bar(stat='identity', position='stack', linewidth=0.1, color='black', width=0.85) +
    #scale_fill_manual(values=c(gencode='#cccccc', novel='#77aaee' )) +
    scale_fill_grey(start=0.9, end=0.3) +
    scale_y_continuous(expand=c(0,0,0.05,0)) +
    labs(x=NULL, y="Cleavage Site Detection Rate\n(Sites/1K Cells)", fill="Stage") +
    theme_bw()
```


---

# Session Info
```{r sesh_info, echo=FALSE}
sessionInfo()
```