---
title: "Cleavage Site Cell Type Expression"
author: "Mervin M Fansler"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document: 
    code_folding: show
    toc: true
    toc_float: true
---

# Initialization
## Libraries
```{r libs, message=FALSE, warning=FALSE}
library(plyranges)
library(tidyverse)
library(magrittr)
```

## Parameters
```{r params}
EPSILON = 30
TPM = 5
N_CTS_LOW = 10
N_CTS_HIGH = 80

FILE_UTROME = sprintf("data/granges/utrome_gr_txs.e%d.t%d.gc25.pas3.f0.9999.w500.Rds", EPSILON, TPM)
FILE_BED = sprintf("data/bed/celltypes/celltypes.e%d.t%d.bed.gz", EPSILON, TPM)
```

## Functions
```{r methods}

```

# Load Data

## Cleavage Sites by Cell Type
```{r load_sites}
gr_sites <- read_bed(FILE_BED) %>% 
    `seqlevelsStyle<-`("UCSC") %>%
    keepStandardChromosomes(pruning.mode="coarse") %>%
    anchor_center() %>%
    mutate(width=EPSILON)
```

## Human UTRome Transcripts
```{r load_txs, message=FALSE, warning=FALSE}
## Load all transcripts
gr_txs <- readRDS(FILE_UTROME)

## focus on cleavage sites
gr_cleavage <- gr_txs %>%
    anchor_3p %>%
    mutate(n_celltypes=count_overlaps_directed(mutate(., width=0), gr_sites)) %>%
    mutate(width=0) %>%
    mutate(origin=ifelse(is_novel, "UTRome", "GENCODE"),
           origin_ud=case_when(
               !is_novel ~ "GENCODE",
               str_detect(transcript_id, "UTR-") ~ "upstream",
               str_detect(transcript_id, "UTR+") ~ "downstream"
           ))
```

## Binning
```{r create_subgroups}
label_origin = c("GENCODE"="Common",
                 "UTRome"="UTRome\nOnly",
                 "GENCODE_only"="GENCODE\nOnly")

df_cleavage <- as_tibble(gr_cleavage) %>%
    mutate(origin_split=ifelse(n_celltypes == 0, "GENCODE_only", origin),
           origin_split=factor(label_origin[origin_split], levels=label_origin),
           n_celltypes_bin=case_when(
               n_celltypes == 0 ~ "none",
               n_celltypes < N_CTS_LOW ~ "low",
               n_celltypes < N_CTS_HIGH ~ "mid",
               TRUE ~ "high"
           ) %>% factor(levels=c("none", "low", "mid", "high")),
           n_celltypes_bin2=case_when(
               n_celltypes == 0 ~ "none",
               n_celltypes < N_CTS_LOW ~ "< 10",
               TRUE ~ "10+"
           ) %>% factor(levels=c("none", "< 10", "10+")) %>% fct_rev())
```

# Plots
## Atlas Origin
```{r plt_few_ct, fig.width=4, fig.height=4}
df_cleavage %>%
    filter(n_celltypes > 0) %>%
    mutate(n_celltypes_bin_many=cut(n_celltypes, breaks=c(0,10, 60, 104), 
                                    include.lowest=TRUE) %>% fct_rev()) %>%
    ggplot(aes(x=origin_split, fill=n_celltypes_bin_many)) +
    geom_bar(color='black', linewidth=0.1) +
    scale_fill_grey(start=0.8, end=0.4) +
    scale_y_continuous(expand=c(0,0,0.05,0)) +
    labs(x=NULL, y="Cleavage Sites", fill="MCA\nCelltypes") +
    theme_bw()
```

```{r plt_few_frac, fig.width=4, fig.height=4}
df_cleavage %>%
    filter(n_celltypes > 0) %>%
    mutate(n_celltypes_bin_many=cut(n_celltypes, breaks=c(0,10, 60, 104), 
                                    include.lowest=TRUE) %>% fct_rev()) %>%
    ggplot(aes(x=origin_split, fill=n_celltypes_bin_many)) +
    geom_bar(position='fill', color='black', linewidth=0.1) +
    scale_fill_grey(start=0.8, end=0.4) +
    scale_y_continuous(expand=c(0,0,0.05,0)) +
    labs(x=NULL, y="Fraction of Cleavage Sites", fill="MCA\nCelltypes") +
    theme_bw()
```

```{r plt_few_ct2, fig.width=3, fig.height=4}
df_cleavage %>%
    filter(n_celltypes > 0) %>%
    ggplot(aes(x=origin_split, fill=n_celltypes_bin2)) +
    geom_bar(color='black', linewidth=0.1, width=0.8) +
    scale_fill_grey(start=0.8, end=0.4) +
    scale_y_continuous(expand=c(0,0,0.05,0)) +
    labs(x=NULL, y="Cleavage Sites", fill="MCA\nCelltypes") +
    theme_bw()
```

```{r plt_few_frac2, fig.width=3, fig.height=4}
df_cleavage %>%
    filter(n_celltypes > 0) %>%
    ggplot(aes(x=origin_split, fill=n_celltypes_bin2)) +
    geom_bar(position='fill', color='black', linewidth=0.1, width=0.8) +
    scale_fill_grey(start=0.8, end=0.4) +
    scale_y_continuous(expand=c(0,0,0.05,0)) +
    labs(x=NULL, y="Fraction of Cleavage Sites", fill="MCA\nCelltypes") +
    theme_bw()
```

### Export
```{r}
ggsave("img/sq/fig1f-mm10-celltypes-fraction.pdf", 
       width=3, height=4, dpi=300)
```

## Cleavage Site Types
```{r plt_full_splits_counts, fig.width=6, fig.height=4}
df_cleavage %>%
    mutate(origin_fine=case_when(
        utr_type == "single" & n_celltypes > 0 ~ "Common\n(single)",
        utr_type == "single" ~ "GENCODE\nOnly\n(single)",
        is_ipa & n_celltypes == 0 ~ "GENCODE\nOnly\n(intronic)",
        is_ipa & origin_split == "Common" ~ "Common\n(intronic)",
        is_ipa ~ "UTRome\nOnly\n(intronic)",
        is_distal & n_celltypes == 0 ~ "GENCODE\nOnly\n(distal)",
        is_distal & origin_split == "Common" ~ "Common\n(distal)",
        is_distal ~ "UTRome\nOnly\n(distal)",
        n_celltypes == 0 ~ "GENCODE\nOnly\n(proximal)",
        origin_split == "Common" ~ "Common\n(proximal)",
        TRUE ~ "UTRome\nOnly\n(proximal)"),
        n_celltypes_bin_many=cut(n_celltypes, breaks=c(0,10, 60, 104), 
                                    include.lowest=TRUE) %>% fct_rev()) %>%
    filter(n_celltypes > 0) %T>% {
        df_counts <<- count(., origin_fine, name="n_genes")
    } %>%
    ggplot(aes(x=origin_fine)) +
    geom_bar(aes(fill=n_celltypes_bin_many), color='black', linewidth=0.1) +
    geom_label(data=df_counts, aes(label=n_genes, x=origin_fine, y=-1000)) +
    scale_fill_grey(start=0.8, end=0.4) +
    scale_y_continuous(expand=c(0.05,0,0.05,0)) +
    labs(x=NULL, y="Cleavage Sites", fill="MCA\nCelltypes") +
    theme_bw()
```

```{r plt_full_splits_fill, fig.width=6, fig.height=4}
df_cleavage %>%
    mutate(origin_fine=case_when(
        utr_type == "single" & n_celltypes > 0 ~ "Common\n(single)",
        utr_type == "single" ~ "GENCODE\nOnly\n(single)",
        is_ipa & n_celltypes == 0 ~ "GENCODE\nOnly\n(intronic)",
        is_ipa & origin_split == "Common" ~ "Common\n(intronic)",
        is_ipa ~ "UTRome\nOnly\n(intronic)",
        is_distal & n_celltypes == 0 ~ "GENCODE\nOnly\n(distal)",
        is_distal & origin_split == "Common" ~ "Common\n(distal)",
        is_distal ~ "UTRome\nOnly\n(distal)",
        n_celltypes == 0 ~ "GENCODE\nOnly\n(proximal)",
        origin_split == "Common" ~ "Common\n(proximal)",
        TRUE ~ "UTRome\nOnly\n(proximal)"),
        n_celltypes_bin_many=cut(n_celltypes, breaks=c(0,10, 60, 104), 
                                    include.lowest=TRUE) %>% fct_rev()) %>%
    filter(n_celltypes > 0) %T>% {
        df_counts <<- count(., origin_fine, name="n_genes")
    } %>%
    ggplot(aes(x=origin_fine)) +
    geom_bar(aes(fill=n_celltypes_bin_many), color='black', linewidth=0.1, position="fill") +
    geom_label(data=df_counts, aes(label=n_genes, x=origin_fine, y=-0.05)) +
    scale_fill_grey(start=0.8, end=0.4) +
    scale_y_continuous(expand=c(0.05,0,0.05,0)) +
    labs(x=NULL, y="Cleavage Sites", fill="MCA\nCelltypes") +
    theme_bw()
```


```{r plt_full_splits_counts2, fig.width=6, fig.height=4}
df_cleavage %>%
    mutate(origin_fine=case_when(
        utr_type == "single" & n_celltypes > 0 ~ "Common\n(single)",
        utr_type == "single" ~ "GENCODE\nOnly\n(single)",
        is_ipa & n_celltypes == 0 ~ "GENCODE\nOnly\n(intronic)",
        is_ipa & origin_split == "Common" ~ "Common\n(intronic)",
        is_ipa ~ "UTRome\nOnly\n(intronic)",
        is_distal & n_celltypes == 0 ~ "GENCODE\nOnly\n(distal)",
        is_distal & origin_split == "Common" ~ "Common\n(distal)",
        is_distal ~ "UTRome\nOnly\n(distal)",
        n_celltypes == 0 ~ "GENCODE\nOnly\n(proximal)",
        origin_split == "Common" ~ "Common\n(proximal)",
        TRUE ~ "UTRome\nOnly\n(proximal)")) %>%
    filter(n_celltypes > 0) %T>% {
        df_counts <<- count(., origin_fine, name="n_genes")
    } %>%
    ggplot(aes(x=origin_fine)) +
    geom_bar(aes(fill=n_celltypes_bin2), color='black', linewidth=0.1, width=0.85) +
    geom_label(data=df_counts, aes(label=n_genes, x=origin_fine, y=-1000)) +
    scale_fill_grey(start=0.8, end=0.4) +
    scale_y_continuous(expand=c(0.05,0,0.05,0)) +
    labs(x=NULL, y="Cleavage Sites", fill="MCA\nCelltypes") +
    theme_bw()
```

```{r plt_full_splits_fill2, fig.width=6, fig.height=4}
df_cleavage %>%
    mutate(origin_fine=case_when(
        utr_type == "single" & n_celltypes > 0 ~ "Common\n(single)",
        utr_type == "single" ~ "GENCODE\nOnly\n(single)",
        is_ipa & n_celltypes == 0 ~ "GENCODE\nOnly\n(intronic)",
        is_ipa & origin_split == "Common" ~ "Common\n(intronic)",
        is_ipa ~ "UTRome\nOnly\n(intronic)",
        is_distal & n_celltypes == 0 ~ "GENCODE\nOnly\n(distal)",
        is_distal & origin_split == "Common" ~ "Common\n(distal)",
        is_distal ~ "UTRome\nOnly\n(distal)",
        n_celltypes == 0 ~ "GENCODE\nOnly\n(proximal)",
        origin_split == "Common" ~ "Common\n(proximal)",
        TRUE ~ "UTRome\nOnly\n(proximal)")) %>%
    filter(n_celltypes > 0) %T>% {
        df_counts <<- count(., origin_fine, name="n_genes")
    } %>%
    ggplot(aes(x=origin_fine)) +
    geom_bar(aes(fill=n_celltypes_bin2), color='black', linewidth=0.1, width=0.85, position="fill") +
    geom_label(data=df_counts, aes(label=n_genes, x=origin_fine, y=-0.05)) +
    scale_fill_grey(start=0.8, end=0.4) +
    scale_y_continuous(expand=c(0.05,0,0.05,0)) +
    labs(x=NULL, y="Cleavage Sites", fill="MCA\nCelltypes") +
    theme_bw()
```

## Extra Cleavage Site Types
```{r plt_extra_splits_counts, fig.width=7, fig.height=4}
df_cleavage %>%
    group_by(gene_id) %>%
    mutate(is_gencode_distal=utr_rank == max(utr_rank[!is_novel]),
           is_extended=origin_ud == 'downstream',
           is_su=if (any(!is_ipa)) { utr_rank == min(utr_rank[!is_ipa]) } else FALSE,
           is_mu=!(is_ipa | is_su | is_gencode_distal | is_extended)) %>%
    ungroup() %>%
    mutate(origin_fine=case_when(
        utr_type == "single" & n_celltypes > 0 ~ "Common\n(single)",
        utr_type == "single" ~ "GENCODE\nOnly\n(single)",
        is_ipa & n_celltypes == 0 ~ "GENCODE\nOnly\n(intronic)",
        is_ipa & origin_split == "Common" ~ "Common\n(intronic)",
        is_ipa ~ "UTRome\nOnly\n(intronic)",
        is_gencode_distal & n_celltypes == 0 ~ "GENCODE\nOnly\n(distal)",
        is_gencode_distal & origin_split == "Common" ~ "Common\n(distal)",
        is_extended ~ "UTRome\nOnly\n(extended)",
        is_su & n_celltypes == 0 ~ "GENCODE\nOnly\n(proximal)",
        is_su & origin_split == "Common" ~ "Common\n(proximal)",
        is_su ~ "UTRome\nOnly\n(proximal)",
        is_mu & n_celltypes == 0 ~ "GENCODE\nOnly\n(medial)",
        is_mu & origin_split == "Common" ~ "Common\n(medial)",
        TRUE ~ "UTRome\nOnly\n(medial)"), 
        n_celltypes_bin_many=cut(n_celltypes, breaks=c(0,10, 60, 104), 
                                    include.lowest=TRUE) %>% fct_rev()) %>%
    filter(n_celltypes > 0) %T>% {
        df_counts <<- count(., origin_fine, name="n_genes")
    } %>%
    ggplot(aes(x=origin_fine)) +
    geom_bar(aes(fill=n_celltypes_bin_many), color='black', linewidth=0.1) +
    geom_label(data=df_counts, aes(label=n_genes, x=origin_fine, y=-600)) +
    scale_fill_grey(start=0.8, end=0.4) +
    scale_y_continuous(expand=c(0.05,0,0.05,0)) +
    labs(x=NULL, y="Cleavage Sites", fill="MCA\nCelltypes") +
    theme_bw()
```


```{r plt_extra_splits_fill, fig.width=7, fig.height=4}
df_cleavage %>%
    group_by(gene_id) %>%
    mutate(is_gencode_distal=utr_rank == max(utr_rank[!is_novel]),
           is_extended=origin_ud == 'downstream',
           is_su=if (any(!is_ipa)) { utr_rank == min(utr_rank[!is_ipa]) } else FALSE,
           is_mu=!(is_ipa | is_su | is_gencode_distal | is_extended)) %>%
    ungroup() %>%
    mutate(origin_fine=case_when(
        utr_type == "single" & n_celltypes > 0 ~ "Common\n(single)",
        utr_type == "single" ~ "GENCODE\nOnly\n(single)",
        is_ipa & n_celltypes == 0 ~ "GENCODE\nOnly\n(intronic)",
        is_ipa & origin_split == "Common" ~ "Common\n(intronic)",
        is_ipa ~ "UTRome\nOnly\n(intronic)",
        is_gencode_distal & n_celltypes == 0 ~ "GENCODE\nOnly\n(distal)",
        is_gencode_distal & origin_split == "Common" ~ "Common\n(distal)",
        is_extended ~ "UTRome\nOnly\n(extended)",
        is_su & n_celltypes == 0 ~ "GENCODE\nOnly\n(proximal)",
        is_su & origin_split == "Common" ~ "Common\n(proximal)",
        is_su ~ "UTRome\nOnly\n(proximal)",
        is_mu & n_celltypes == 0 ~ "GENCODE\nOnly\n(medial)",
        is_mu & origin_split == "Common" ~ "Common\n(medial)",
        TRUE ~ "UTRome\nOnly\n(medial)"), 
        n_celltypes_bin_many=cut(n_celltypes, breaks=c(0,10, 60, 104), 
                                    include.lowest=TRUE) %>% fct_rev()) %>%
    filter(n_celltypes > 0) %T>% {
        df_counts <<- count(., origin_fine, name="n_genes")
    } %>%
    ggplot(aes(x=origin_fine)) +
    geom_bar(aes(fill=n_celltypes_bin_many), color='black', linewidth=0.1, position="fill") +
    geom_label(data=df_counts, aes(label=n_genes, x=origin_fine, y=-0.05)) +
    scale_fill_grey(start=0.8, end=0.4) +
    scale_y_continuous(expand=c(0.05,0,0.05,0)) +
    labs(x=NULL, y="Cleavage Sites", fill="MCA\nCelltypes") +
    theme_bw()
```


```{r plt_extra_splits_counts2, fig.width=7, fig.height=4}
df_cleavage %>%
    group_by(gene_id) %>%
    mutate(is_gencode_distal=utr_rank == max(utr_rank[!is_novel]),
           is_extended=origin_ud == 'downstream',
           is_su=if (any(!is_ipa)) { utr_rank == min(utr_rank[!is_ipa]) } else FALSE,
           is_mu=!(is_ipa | is_su | is_gencode_distal | is_extended)) %>%
    ungroup() %>%
    mutate(origin_fine=case_when(
        utr_type == "single" & n_celltypes > 0 ~ "Common\n(single)",
        utr_type == "single" ~ "GENCODE\nOnly\n(single)",
        is_ipa & n_celltypes == 0 ~ "GENCODE\nOnly\n(intronic)",
        is_ipa & origin_split == "Common" ~ "Common\n(intronic)",
        is_ipa ~ "UTRome\nOnly\n(intronic)",
        is_gencode_distal & n_celltypes == 0 ~ "GENCODE\nOnly\n(distal)",
        is_gencode_distal & origin_split == "Common" ~ "Common\n(distal)",
        is_extended ~ "UTRome\nOnly\n(extended)",
        is_su & n_celltypes == 0 ~ "GENCODE\nOnly\n(proximal)",
        is_su & origin_split == "Common" ~ "Common\n(proximal)",
        is_su ~ "UTRome\nOnly\n(proximal)",
        is_mu & n_celltypes == 0 ~ "GENCODE\nOnly\n(medial)",
        is_mu & origin_split == "Common" ~ "Common\n(medial)",
        TRUE ~ "UTRome\nOnly\n(medial)")) %>%
    filter(n_celltypes > 0) %T>% {
        df_counts <<- count(., origin_fine, name="n_genes")
    } %>%
    ggplot(aes(x=origin_fine)) +
    geom_bar(aes(fill=n_celltypes_bin2), color='black', linewidth=0.1, width=0.85) +
    geom_label(data=df_counts, aes(label=n_genes, x=origin_fine, y=-600)) +
    scale_fill_grey(start=0.8, end=0.4) +
    scale_y_continuous(expand=c(0.05,0,0.05,0)) +
    labs(x=NULL, y="Cleavage Sites", fill="MCA\nCelltypes") +
    theme_bw()
```


```{r plt_extra_splits_fill2, fig.width=7, fig.height=4}
df_cleavage %>%
    group_by(gene_id) %>%
    mutate(is_gencode_distal=utr_rank == max(utr_rank[!is_novel]),
           is_extended=origin_ud == 'downstream',
           is_su=if (any(!is_ipa)) { utr_rank == min(utr_rank[!is_ipa]) } else FALSE,
           is_mu=!(is_ipa | is_su | is_gencode_distal | is_extended)) %>%
    ungroup() %>%
    mutate(origin_fine=case_when(
        utr_type == "single" & n_celltypes > 0 ~ "Common\n(single)",
        utr_type == "single" ~ "GENCODE\nOnly\n(single)",
        is_ipa & n_celltypes == 0 ~ "GENCODE\nOnly\n(intronic)",
        is_ipa & origin_split == "Common" ~ "Common\n(intronic)",
        is_ipa ~ "UTRome\nOnly\n(intronic)",
        is_gencode_distal & n_celltypes == 0 ~ "GENCODE\nOnly\n(distal)",
        is_gencode_distal & origin_split == "Common" ~ "Common\n(distal)",
        is_extended ~ "UTRome\nOnly\n(extended)",
        is_su & n_celltypes == 0 ~ "GENCODE\nOnly\n(proximal)",
        is_su & origin_split == "Common" ~ "Common\n(proximal)",
        is_su ~ "UTRome\nOnly\n(proximal)",
        is_mu & n_celltypes == 0 ~ "GENCODE\nOnly\n(medial)",
        is_mu & origin_split == "Common" ~ "Common\n(medial)",
        TRUE ~ "UTRome\nOnly\n(medial)")) %>%
    filter(n_celltypes > 0) %T>% {
        df_counts <<- count(., origin_fine, name="n_genes")
    } %>%
    ggplot(aes(x=origin_fine)) +
    geom_bar(aes(fill=n_celltypes_bin2), color='black', linewidth=0.1, width=0.85, position="fill") +
    geom_label(data=df_counts, aes(label=n_genes, x=origin_fine, y=-0.05)) +
    scale_fill_grey(start=0.8, end=0.4) +
    scale_y_continuous(expand=c(0.05,0,0.05,0)) +
    labs(x=NULL, y="Cleavage Sites", fill="MCA\nCelltypes") +
    theme_bw()
```


---

# Session Info
```{r sesh_info, echo=FALSE}
sessionInfo()
```